# $Id$

include ../config.mk

IMGFILES = inspire_logo.png invenio_inspire.css
LIBFILES = webstyle_templates_inspire.py

all: 
	@echo "Done."

test:
	@echo "Not Implemented."

install:
	$(INSTALL) -m 664 $(IMGFILES) $(WEBDIR)/img
	$(INSTALL) -m 664 $(LIBFILES) $(LIBDIR)/python/invenio

# end of file
