include ../config.mk
-include ../config-local.mk

SCRIPTBINFILES = rt
SCRIPTBINDIR = $(BINDIR)

# main targets:

all:
	@echo "Done."
clean:
	@echo "Done."

install:
	$(INSTALL) $(SCRIPTBINFILES) $(SCRIPTBINDIR)

# end of file
