# $Id$

include ../../config.mk
-include ../../config-local.mk

LIBFILES = bibtaskutils.py

LIBDIR = $(PREFIX)/lib/python/invenio/

all:
	@echo "Done."

test:
	@echo "Nothing to test."

install:
	$(INSTALL) -m 664 $(LIBFILES) $(LIBDIR)
