CFG_APSHARVEST_FULLTEXT_URL = "http://harvest.aps.org/bagit/articles/%(doi)s/apsxml"
CFG_APSHARVEST_REQUEST_TIMEOUT = 2.0
CFG_APSHARVEST_SEARCH_COLLECTION = "HEP"
CFG_APSHARVEST_RECORD_DOI_TAG = "0247_a"
CFG_APSHARVEST_MD5_FILE = "manifest-md5.txt"
CFG_APSHARVEST_FFT_DOCTYPE = "APS"
CFG_APSHARVEST_BUNCH_SIZE = 100
