# $Id$

include ../config.mk
-include ../config-local.mk

LIBFILES = *.py

all:
	@echo "Done."

test:
	@echo "Nothing to test."

install:
	$(INSTALL) -m 664 $(LIBFILES) $(LIBDIR)/python/invenio

clean:
	@rm -f *.orig *~

# end of file
