# $Id$

include ../../config.mk

BFOFILES = *.bfo
BFODIR = $(ETCDIR)/bibformat/output_formats

all:
	@echo "Done."

test:
	@echo "Not implemented."

install:
	$(INSTALL) -m 664 $(BFOFILES) $(BFODIR)

clean:
	@rm -f *.orig *~
