include ../config.mk

XMLFILES = *.xml
XMLDIR = $(ETCDIR)/bibedit/record_templates

all:
	@echo "Done."

test:
	@echo "Not implemented."

install:
	$(INSTALL) -m 664 $(XMLFILES) $(XMLDIR)

clean:
	@rm -f *.orig *~
