# $Id$

include ../../config.mk

BFTFILES = *.bft
BFTDIR = $(ETCDIR)/bibformat/format_templates

all:
	@echo "Done."

test:
	@echo "Not implemented."

install:
	$(INSTALL) -m 664 $(BFTFILES) $(BFTDIR)

clean:
	@rm -f *.orig *~
