include ../../config.mk
-include ../../config-local.mk

PYLIBS = arxiv_curation.py
PYLIBDIR = $(LIBDIR)/python/invenio/bibcatalog_ticket_templates/

# main targets:

all:
	@echo "Done."
clean:
	@echo "Done."

install:
	mkdir -p $(PYLIBDIR)
	$(INSTALL) $(PYLIBS) $(PYLIBDIR)

# end of file
