# $Id$

include ../../config.mk
-include ../../config-local.mk

IMGFILES = *.png *.jpg

all:
	@echo "Done."

test:
	@echo "Nothing to test."

install:
	$(INSTALL) -m 664 $(IMGFILES) $(WEBDIR)/img

clean:
	@rm -f *.orig *~

# end of file
